;;; feature-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from feature-mode.el

(autoload 'feature-mode "feature-mode"
"Major mode for editing Gherkin (i.e. Cucumber) user stories.

In addition to any hooks its parent mode `text-mode' might have run, this mode
runs the hook `feature-mode-hook', as the final or penultimate step during
initialization.

\\{feature-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.feature\\'" . feature-mode))
(register-definition-prefixes "feature-mode" '("feature-"))

;;; End of scraped data

(provide 'feature-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; feature-mode-autoloads.el ends here
