;;; scad-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ob-scad.el

(register-definition-prefixes "ob-scad" '("org-babel-"))


;;; Generated autoloads from scad-mode.el

(add-to-list 'auto-mode-alist '("\\.scad\\'" . scad-mode))
(autoload 'scad-mode "scad-mode"
"Major mode for editing OpenSCAD code.

In addition to any hooks its parent mode `prog-mode' might have run, this mode
runs the hook `scad-mode-hook', as the final or penultimate step during
initialization.

\\{scad-mode-map}" t)
(register-definition-prefixes "scad-mode" '("scad-"))

;;; End of scraped data

(provide 'scad-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; scad-mode-autoloads.el ends here
