;;; suggest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from suggest.el

(autoload 'suggest "suggest" "\
Open a Suggest buffer that provides suggestions for the inputs
and outputs given." t)
(autoload 'suggest-update "suggest" "\
Update the suggestions according to the latest inputs/output given." t)
(register-definition-prefixes "suggest" '("suggest-"))


;;; Generated autoloads from suggest-bench.el

(register-definition-prefixes "suggest-bench" '("suggest-"))

;;; End of scraped data

(provide 'suggest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; suggest-autoloads.el ends here
