;;; org-pomodoro-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from org-pomodoro.el

(autoload 'org-pomodoro "org-pomodoro" "\
Start a new pomodoro or stop the current one.

When no timer is running for `org-pomodoro` a new pomodoro is started and
the current task is clocked in.  Otherwise EMACS will ask whether we´d like to
kill the current timer, this may be a break or a running pomodoro.

(fn &optional ARG)" t)
(register-definition-prefixes "org-pomodoro" '("org-pomodoro-"))


;;; Generated autoloads from org-pomodoro-pidgin.el

(register-definition-prefixes "org-pomodoro-pidgin" '("org-pom"))

;;; End of scraped data

(provide 'org-pomodoro-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-pomodoro-autoloads.el ends here
