;;; markdown-preview-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from markdown-preview-mode.el

(autoload 'markdown-preview-open-browser "markdown-preview-mode" "\
Open the `markdown-preview' in the browser." t)
(autoload 'markdown-preview-cleanup "markdown-preview-mode" "\
Cleanup `markdown-preview' mode." t)
(autoload 'markdown-preview-mode "markdown-preview-mode" "\
Markdown preview mode.

This is a minor mode.  If called interactively, toggle the
`Markdown-Preview mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `markdown-preview-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "markdown-preview-mode" '("markdown-preview-"))

;;; End of scraped data

(provide 'markdown-preview-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; markdown-preview-mode-autoloads.el ends here
