;;; caml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from caml.el

(autoload 'caml-mode "caml" "\
Major mode for editing OCaml code.

(fn)" t)
(register-definition-prefixes "caml" '("caml-"))


;;; Generated autoloads from caml-font.el

(register-definition-prefixes "caml-font" '("caml-font-" "inferior-caml-"))


;;; Generated autoloads from caml-font-old.el

(register-definition-prefixes "caml-font-old" '("Stop" "caml-" "inferior-caml-"))


;;; Generated autoloads from caml-help.el

(register-definition-prefixes "caml-help" '("caml-" "ocaml-"))


;;; Generated autoloads from caml-types.el

(register-definition-prefixes "caml-types" '("caml-"))


;;; Generated autoloads from camldebug.el

(defvar camldebug-command-name "ocamldebug" "\
*Pathname for executing camldebug.")
(autoload 'camldebug "camldebug" "\
Run camldebug on program FILE in buffer *camldebug-FILE*.
The directory containing FILE becomes the initial working directory
and source-file directory for camldebug.  If you wish to change this, use
the camldebug commands `cd DIR' and `directory'.

(fn FILE)" t)
(register-definition-prefixes "camldebug" '("camldebug-" "current-camldebug-buffer" "def-camldebug"))


;;; Generated autoloads from inf-caml.el

(register-definition-prefixes "inf-caml" '("caml-" "inferior-caml-" "run-caml"))

;;; End of scraped data

(provide 'caml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; caml-autoloads.el ends here
