;;; feature-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from feature-mode.el

(autoload 'feature-mode "feature-mode" "\
Major mode for editing plain text stories" t)
(add-to-list 'auto-mode-alist '("\\.feature\\'" . feature-mode))
(register-definition-prefixes "feature-mode" '("build-keyword-matcher" "can-run-bundle" "expand-home-shellism" "feature-" "given-when-then-wordlength" "load-gherkin-i10n" "parse-gherkin-l10n" "project-file-exists" "should-run-docker-compose" "try-find-next"))

;;; End of scraped data

(provide 'feature-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; feature-mode-autoloads.el ends here
