;;; haml-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from haml-mode.el

(autoload 'haml-mode "haml-mode"
"Major mode for editing Haml files.

\\{haml-mode-map}

In addition to any hooks its parent mode `prog-mode' might have run, this mode
runs the hook `haml-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.haml\\'" . haml-mode))
(register-definition-prefixes "haml-mode" '("haml-"))

;;; End of scraped data

(provide 'haml-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; haml-mode-autoloads.el ends here
