;;; flycheck-ocaml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from flycheck-ocaml.el

(autoload 'flycheck-ocaml-setup "flycheck-ocaml" "\
Setup Flycheck OCaml.

Add `ocaml-merlin' to `flycheck-checkers'." t)
(register-definition-prefixes "flycheck-ocaml" '("flycheck-"))

;;; End of scraped data

(provide 'flycheck-ocaml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-ocaml-autoloads.el ends here
