;;; fxrd-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cbnot-mode.el

(autoload 'cbnot-mode "cbnot-mode"
"Major mode for editing CBNOT fixed field width files.

\\{fxrd-mode-map}

In addition to any hooks its parent mode `fxrd-mode' might have run, this mode
runs the hook `cbnot-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.cbnot\\($\\|\\.\\)" . cbnot-mode))
(register-definition-prefixes "cbnot-mode" '("cbnot-spec"))


;;; Generated autoloads from fxrd-mode.el

(register-definition-prefixes "fxrd-mode" '("current-" "disable-fxrd-mode" "fxrd-" "get-" "line-type"))


;;; Generated autoloads from fxrd-validators.el

(register-definition-prefixes "fxrd-validators" '("fxrd-" "validation-error"))


;;; Generated autoloads from nacha-mode.el

(autoload 'nacha-mode "nacha-mode"
"Major mode for editing NACHA fixed field width files.

\\{fxrd-mode-map}

In addition to any hooks its parent mode `fxrd-mode' might have run, this mode
runs the hook `nacha-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.nacha\\($\\|\\.\\)" . nacha-mode))
(register-definition-prefixes "nacha-mode" '("nacha-spec"))


;;; Generated autoloads from rm37-mode.el

(autoload 'rm37-mode "rm37-mode"
"Major mode for editing RM37 fixed field width files.

\\{fxrd-mode-map}

In addition to any hooks its parent mode `fxrd-mode' might have run, this mode
runs the hook `rm37-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.rm37\\($\\|\\.\\)" . rm37-mode))
(add-to-list 'auto-mode-alist '("\\.rm39\\($\\|\\.\\)" . rm37-mode))
(register-definition-prefixes "rm37-mode" '("rm37-spec"))


;;; Generated autoloads from sample-mode.el

(autoload 'sample-mode "sample-mode"
"Major mode for editing SAMPLE fixed field width files.

\\{fxrd-mode-map}

In addition to any hooks its parent mode `fxrd-mode' might have run, this mode
runs the hook `sample-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.fxrd-sample\\($\\|\\.\\)" . sample-mode))
(register-definition-prefixes "sample-mode" '("sample-spec"))


;;; Generated autoloads from tso6-mode.el

(autoload 'tso6-mode "tso6-mode"
"Major mode for editing TSO6 fixed field width files.

\\{fxrd-mode-map}

In addition to any hooks its parent mode `fxrd-mode' might have run, this mode
runs the hook `tso6-mode-hook', as the final or penultimate step during
initialization." t)
(add-to-list 'auto-mode-alist '("\\.tso6\\($\\|\\.\\)" . tso6-mode))
(add-to-list 'auto-mode-alist '("\\.tso8\\($\\|\\.\\)" . tso6-mode))
(register-definition-prefixes "tso6-mode" '("tso6-spec"))

;;; End of scraped data

(provide 'fxrd-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fxrd-mode-autoloads.el ends here
