;;; gnuplot-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gnuplot-mode.el

(autoload 'gnuplot-mode "gnuplot-mode" "\
Major mode for editing gnuplot files

(fn)" t)
(dolist (pattern '("\\.gnuplot\\'" "\\.gp\\'")) (add-to-list 'auto-mode-alist (cons pattern 'gnuplot-mode)))
(autoload 'gnuplot-compile "gnuplot-mode" "\
Runs gnuplot -persist as a synchronous process and passes the
current buffer to it.  Buffer must be visiting a file for it to
work." t)
(autoload 'gnuplot-run-region "gnuplot-mode" "\
Send region to gnuplot, ensuring a final newline.  Doesn't
require buffer to be visiting a file.

(fn START END)" t)
(autoload 'gnuplot-run-buffer "gnuplot-mode" "\
Send buffer to gnuplot, ensuring a final newline.  Doesn't
require buffer to be visiting a file." t)
(register-definition-prefixes "gnuplot-mode" '("gnuplot-" "gp-"))

;;; End of scraped data

(provide 'gnuplot-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gnuplot-mode-autoloads.el ends here
